services:
  api:
    restart: always
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    build: 
      context: ./api/django_project
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./api/django_project:/app
    ports:
      - "8000:8000"
  
  frontend:
    restart: always
    container_name: frontend
    command: npm start
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - api
      